name: C/C++ CI

on:
  push:
    - master
    

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
    matrix:
      of: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
